version: "3.7"
 
# USAGE: 
# Create and start the cluster: docker-compose up -d 
# Tear down the cluster: docker-compose down 
# Remove everything including the volumes: docker-compose down -v  
#
# Backup:
# docker exec -t your-container pg_dumpall -c -U postgres > your-backup.bkp
#
# Restore:
# cat your_backup.bkp | docker exec -i your-container psql -U postgres -d yout-database -W
#
# Shell:
# docker exec -it yout-container <cmd>
services: 
  framework:
    container_name: sensoriando_webservice
    image: python:3.8
    build: 
        context: ./
        dockerfile: Dockerfile
    env_file:
        - .env
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT} ${DJANGO_PARAMS}
    working_dir: /usr/src/app
    ports: 
        - ${DJANGO_PORT}:$(DJANGO_PORT)
    volumes:
        - .:/usr/src/app
    networks:
        - sensoriando

networks:
    sensoriando:
        external: true

