# Generated by Django 3.0.5 on 2020-04-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('ispublic', models.BooleanField()),
                ('status', models.BooleanField()),
                ('usetrigger', models.BooleanField()),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'sensors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensorsparams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sensorsparams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensorsunits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('initial', models.CharField(blank=True, max_length=5, null=True)),
                ('precision', models.SmallIntegerField(blank=True, null=True)),
                ('isdefault', models.BooleanField()),
                ('expression', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sensorsunits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(unique=True)),
                ('isrelay', models.BooleanField()),
            ],
            options={
                'db_table': 'things',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thingsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('qos', models.IntegerField()),
                ('retained', models.BooleanField()),
                ('payload', models.TextField()),
            ],
            options={
                'db_table': 'thingsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thingsflags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'thingsflags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thingsparams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'thingsparams',
                'managed': False,
            },
        ),
    ]
