# Generated by Django 2.2 on 2018-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='local',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='localized',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
